server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup_plazoleta
    username: root
    password: 1093300651

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Plazoleta"
appVersion: "1.0.0"
hystrix:
  shareSecurityContext: true
feign:
  hystrix:
    enabled: true
